import "./globals.css";
import Footer from "@/components/Footer/Footer";
import { CursorProvider } from "@/contexts/CursorContext/CursorContext";
import { ReactNode } from "react";

export const metadata = {
  title: "Lewis J - Designer & Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" data-theme="landing">
      <CursorProvider>
        <body>
          <div className="w-screen overflow-x-hidden">
            <span className="min-h-screen">{children}</span>
            <Footer />
          </div>
        </body>
      </CursorProvider>
    </html>
  );
}
