import "./globals.css";
import Header from "@/components/atoms/Header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-dark-50 w-screen">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
